### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by majidalik** [phunware/maas-location-android-sdk#26]
java.lang.NullPointerException: interceptor com.phunware.core.internal.JWTAuthInterceptor@32af812 returned null
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:157)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by tstump-phunware** [comment]
Closing, as this should be resolved in using version 4.4.0 or newer
